import cv2
import numpy 

def find_shaddow(img_depth,img_raw,color_L,color_H):
    #This function try to find out all shaddows in the depth image

    # Mask the shaddow by static color
    image_mask = cv2.inRange(img_depth,color_L,color_H)

    # Search the contour inside the masked image
    image_contour,contours,hierarchy = cv2.findContours(image_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    
    # Draw them out
    cv2.drawContours(img_raw, contours,-1,(0,255,0),3)

    return contours

def find_target_contour(contours,img_depth_img_raw):
    #This function try to find out the shaddow generated by the target object

    # TO-DO
    
    return 0

